// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/about": {
    params: {};
  };
  "/factory": {
    params: {};
  };
  "/contactus": {
    params: {};
  };
  "/partners": {
    params: {};
  };
  "/buyinghouse": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/about" | "/factory" | "/contactus" | "/partners" | "/buyinghouse";
  };
  "./layouts/MainLayout.tsx": {
    id: "layouts/MainLayout";
    page: "/" | "/about" | "/factory" | "/contactus" | "/partners" | "/buyinghouse";
  };
  "../app/routes/home.tsx": {
    id: "../app/routes/home";
    page: "/";
  };
  "./components/AboutUs.tsx": {
    id: "components/AboutUs";
    page: "/about";
  };
  "./components/factory.tsx": {
    id: "components/factory";
    page: "/factory";
  };
  "./components/ContactPage.tsx": {
    id: "components/ContactPage";
    page: "/contactus";
  };
  "./components/GlobalPartners.tsx": {
    id: "components/GlobalPartners";
    page: "/partners";
  };
  "./components/BuyingHouse.tsx": {
    id: "components/BuyingHouse";
    page: "/buyinghouse";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "layouts/MainLayout": typeof import("./app/./layouts/MainLayout.tsx");
  "../app/routes/home": typeof import("./app/../app/routes/home.tsx");
  "components/AboutUs": typeof import("./app/./components/AboutUs.tsx");
  "components/factory": typeof import("./app/./components/factory.tsx");
  "components/ContactPage": typeof import("./app/./components/ContactPage.tsx");
  "components/GlobalPartners": typeof import("./app/./components/GlobalPartners.tsx");
  "components/BuyingHouse": typeof import("./app/./components/BuyingHouse.tsx");
};